### ISSUE TITLE
`execCommand` tests are flaky

### ISSUE THREAD

**Issue by morey-tech** [argocd-diff-action/argocd-diff-action#20]
On the upgrade to Node 18, it will break one unit test due to a change in the expected output.
See d66354c24507175a8c7e942625947e26b3272796 for the fix.

```
  ● execCommand returns an err on failure

    expect(received).rejects.toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

      Object {
    -   "stderr": "/bin/sh: 1: badBinary: not found
    +   "stderr": "/bin/sh: badBinary: command not found
      ",
        "stdout": "",
      }
```

**Comment by morey-tech** [comment]
This issue is reproducing on my system while running node `16.9.1`. The main problem here seems to be that the tests for `execCommand` are testing integration with the system running the application and not just the function itself.

**Comment by Voziv** [comment]
I don't believe this is an issue anymore. I've upgraded everything to node 20/node 22 and it's passing tests currently. Feel free to re-open if it comes up again
