### ISSUE TITLE
`--plaintext` support

### ISSUE THREAD

**Issue by fcrespofastly** [argocd-diff-action/argocd-diff-action#73]
Currently even if you pass `--plaintext` in the `argocd-extra-cli-args` input the api gets hit on 443 port. If you run argocd behind an ingress controller you may want to terminate TLS at ingress and expose a ClusterIP service for ArgoCD at port 80.

We run in-cluster GHA runners and we would rather just hit that ClusterIP service that going outside to then hit ingress and then the pod.

Currently `https://` it's hardcoded here: https://github.com/argocd-diff-action/argocd-diff-action/blob/main/src/argocd/ArgoCDServer.ts#L69 

Which causes builds to fail when targetting internal kubernetes services.

**Comment by Voziv** [comment]
Updated line number: https://github.com/argocd-diff-action/argocd-diff-action/blob/main/src/argocd/ArgoCDServer.ts#L75

`const url = `https://${this.fqdn}/api/${endpoint}?${params.join('&')}}`;`

I can see two ways of solving this

Option A: Include the protocol as part of the FQDN. It'd be a breaking change but doesn't seem unreasonable to do.

Option B: Add a `tls: false` input parameter that would change it to use http and automatically add `--plaintext`
